# FROM ubuntu:jammy

# RUN apt-get update && apt-get install -y curl && \
#     curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
#     apt-get install -y nodejs && node -v && npm -v

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

ENV PORT=5173

EXPOSE 5173

CMD [ "serve", "-s", "dist", "-l", "5173" ]
